### ISSUE TITLE
QA_Searching and Sorting_Experiment

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#112]
Defect Description:
In the experiment page of  "Searching and Sorting"  experiment,if we select the Hint level from the dropdown list present at the hint field and now if we change the hint level(eg:from hint1 to hint4), the hint/script is not changing instead the modified hint level script/hint should be displayed on the screen.

Actual Result:
In the experiment page of "Searching and Sorting" experiment,if we select the Hint level from the dropdown list present at the hint field and now if we change the hint level(eg:from hint1 to hint4), the hint/script is not modified.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Searching%20and%20Sorting/Searching%20and%20Sorting_15_Experiment_p2.org

![10](https://cloud.githubusercontent.com/assets/14869397/11437063/88288d1c-9510-11e5-8488-2510008dad59.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed

**Comment by kolliSuman** [comment]
when we change the hint level from hint 3 to hint 0, the code is not changing, so the QA team is reopening this issue

![hint8](https://cloud.githubusercontent.com/assets/14869397/13134783/4b28d622-d630-11e5-88ee-158c994174c3.png)

**Comment by BSravanthi** [comment]
The issue is not resolved. Code is not changing when we change the hint level from 3 to 0

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
